### ISSUE TITLE
Configure "master" as the default branch on GitHub

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-registry-py#11]
In my opinion, we should delete the "develop" branch as well. I can't do this, as I don't have enough permissions. @pwalsh could you do it when you have a few minutes?

**Comment by pwalsh** [comment]
Agreed. While many of us have been following Git Flow and having a distinct `develop` branch as well as `master`, it is largely redundant of we have feature branches, decent tests, and code reviews https://github.com/okfn/coding-standards

So, I've now set default to master: please delete the develop branch.

**Comment by vitorbaptista** [comment]
Done
