### ISSUE TITLE
Remove from PyPI

### ISSUE THREAD

**Issue by Zearin** [okfn/datapackage-registry-py#14]
I just found this repo via the PyPI link here:

https://pypi.python.org/pypi/datapackage-registry

If this package is deprecated, please consider removing the deprecated entries from PyPI.  (People should then find just the current package instead. ☻)

Thanks!

**Comment by pwalsh** [comment]
Hi @Zearin I'm not sure that is a good idea. We don't want to break installs for code that may depend on those earlier versions.

**Comment by Zearin** [comment]
In that case, I recommend that you: 

- change its Trove Classifier status to `Development Status :: 7 - Inactive`
- in the package that supersedes this one, add the `obsoletes=['datapackage-registry==0.4.0']` keyword argument to `setup(…)`

**Comment by pwalsh** [comment]
@Zearin great, thanks will do that.

**Comment by pwalsh** [comment]
Hey @vitorbaptista see above. can you squeeze this in one morning in the next week or so?

**Comment by vitorbaptista** [comment]
@Zearin Thanks for the suggestion. I wasn't aware of the `obsoletes` option in setup.py.

@pwalsh Will do :+1:

**Comment by vitorbaptista** [comment]
I've added your suggestions, @Zearin, to both `datapackage-validate` and `datapackage-registry`. Whenever we push `datapackage` to PyPI, it'll also have the `obsoletes` notice (https://github.com/frictionlessdata/datapackage-py/commit/beb997d4b4f4a78d2d204f67852389b9c9b800e5)

Thanks for your contribution.

**Comment by Zearin** [comment]
Awesome!  Glad to hear it.  😃

**Comment by vitorbaptista** [comment]
Unfortunately, I couldn't use the `obsoletes` in `setup.py` because Python fails with `ValueError: expected parenthesized list`. It seems it doesn't support names with dashes (for example https://github.com/miracle2k/webassets/issues/39). Because of this, I reverted the commit in `datapackage-py`.
