### ISSUE TITLE
Work offline by default

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-registry-py#2]
I've been thinking on how to add the registry to https://github.com/okfn/datapackage-py and thought about a solution. My two hard requirements while thinking about this were:

1. It should work offline;
2. It shouldn't do any HTTP requests unless explicitly asked.

To do that, we would need a local registry and schema cache.

# Generating the cache

The cache it should be populated when creating this package, so everything that this package needs to be useful is package with it. This could be done either by adding the registry as a `git-submodule`, or by downloading the files when building the package (check https://github.com/vitorbaptista/pyppd/blob/master/setup.py#L6-L18 for an example). I prefer using `git-submodules`, because we then guarantee that this package's builds are always the same, no matter if we build it today or in a year from now. Whenever we want to update the default cache, we can upload a new version to pypi.

If we change the https://github.com/dataprotocols/registry a bit, this process gets easier. Currently, the registry looks like:

| id | title | schema | specification |
| --- | --- | --- | --- |
| base | Data Package | https://rawgit.com/dataprotocols/schemas/master/data-package.json  | http://dataprotocols.org/data-packages |
| tabular | Tabular Data Package | https://rawgit.com/dataprotocols/schemas/master/tabular-data-package.json | http://dataprotocols.org/tabular-data-package/ |
| fiscal | Fiscal Data Package | https://rawgit.com/dataprotocols/schemas/master/fiscal-data-package.json | http://fiscal.dataprotocols.org/spec/ |

This tells us how to find the schemas through their URL, but we don't know how to find them locally. If we merged the https://raw.githubusercontent.com/dataprotocols/registry and https://github.com/dataprotocols/schemas repositories, having a file structure similar to:

```
./registry.csv
./data-package.json
./tabular-data-package.json
./fiscal-data-package.json
```

Then we could add a new column to `registry.csv` which defines the relative path to the schema based on the registry's path. For example:

| id | title | schema | specification | relative_path |
| --- | --- | --- | --- | --- |
| base | ... | ... | ... | data-package.json |
| tabular | ... | ... | ... | tabular-data-package.json |
| fiscal | ... | ... | ... | fiscal-data-package.json |

This `relative_path` works both if the `registry.csv` is being accessed locally or through its URL. As in, if the `registry.csv` is living at `https://github.com/dataprotocols/schemas/blob/master/registry.csv` and I want to get the `tabular` datapackage, I would hit `https://github.com/dataprotocols/schemas/blob/master/tabular-data-package.json`. If it's living on my file system, I would hit `/path/to/registry/tabular-data-package.json`.

Without this `relative_path` column, we would have to keep track of the mapping between the schema's `id` and its path in the local cache. It shouldn't be a big deal, but leaving this to the `registry.csv` simplifies things.

# Updating the cache

To update the registry, the user could either call `datapackage_registry.update()`, upgrade the package on pypi (if we had already updated the package), or even call an hypothetical `datapackage registry update` CLI command.

As a user of `datapackage_registry` (i.e. https://github.com/okfn/datapackage-py), I won't have to think about these issues, as they'll be handled by the registry.

This same pattern can be replicated on other languages by building a `npm` package as well.

# Third-party registries

This solution doesn't cache schemas available in third-party registries. It could be done by namespacing the local cache, allowing to have multiple registries in it, but I'm not sure if it's something useful to spend time with. I suppose most of the schemas will eventually be added to the main registry.

**Comment by pwalsh** [comment]
Hey @vitorbaptista great ideas. About 3rd party registries, we don't need to support it now - we'll defer that problem for later, if it ever actually becomes a problem.

For the rest - seems like a good idea and we can give it a try asap.

**Comment by vitorbaptista** [comment]
Cool, @pwalsh. I'll begin implementing it and send a pull request for review :+1:

**Comment by vitorbaptista** [comment]
Currently, the API only supports getting the registry itself, and not the actual profiles. To do that, I'm thinking on doing something like:

```python
import datapackage_registry

registry = datapackage_registry.Registry()  # You could pass a string with a URL
                                            # or filepath here to change the registry.
                                            # By default it gets from the local cache.
print registry.profiles
# {
#     'base': {
#         'id': 'base',
#         'schema': 'https://rawgit.com/dataprotocols/schemas/master/data-package.json',
#         'specification': 'http://dataprotocols.org/data-packages',
#         'title': 'Data Package'
#     },
#     'tabular': {
#         'id': 'tabular',
#         'schema': 'https://rawgit.com/dataprotocols/schemas/master/tabular-data-package.json',
#         'specification': 'http://dataprotocols.org/tabular-data-package/',
#         'title': 'Tabular Data Package'
#    },
#    ...
# }

print registry.get('base')
# {
#     '$schema': 'http://json-schema.org/draft-04/schema#',
#     'title': 'DataPackage',
#     'description': 'DataPackage is a format and specification for convenient delivery, installation and management of data. This is the base profile for DataPackage.',
#     'type': 'object',
#     ...
# }
```

This hides the complexity of fetching HTTP requests or loading the cache.

**Comment by pwalsh** [comment]
@vitorbaptista the problem with that is you don't get the other data. like the link to the spec. In [DataPackagist](https://github.com/okfn/datapackagist), we expose some of the other info in the UI. so, we'd need an API for retrieving all fields. One possibility would be the resolve the schema URL into the full object and inline it, so:

print registry.get('base')
# {
#     ... other fields from the csv,
#     'schema': {
#        '$schema': 'http://json-schema.org/draft-04/schema#',
#       'title': 'DataPackage',
#       'description': 'DataPackage is a format and specification for convenient delivery, installation and management of data. This is the base profile for DataPackage.',
#       'type': 'object',
#       ...
#3       }
# }

**Comment by vitorbaptista** [comment]
@pwalsh You can get that from `registry.profiles`. The separation is that `registry.profiles` maintain the profiles' metadata and, if you want a single profile, you'd use `registry.get('profile_id')`. What do you think?

**Comment by pwalsh** [comment]
@vitorbaptista great. Go ahead on this.

**Comment by vitorbaptista** [comment]
This is almost done. The remaining piece is allowing the user to update hers local cache (https://github.com/okfn/datapackage-registry-py/issues/6). We decided we won't allow caching third-party registries, so that's it :+1:
