### ISSUE TITLE
Instead of accepting a configuration dict, take the actual values instead

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-registry-py#4]
Now, `Registry()` takes a configuration `dict`, but just uses its `backend` attribute. Receiving a dict instead of actual attributes is bad because it makes the code less self-explanatory. For instance, if I read that a method signature looks like `Registry(user_config=None)`, I know it takes a configuration object, but I don't know the structure of that object, what attributes it requires, etc. I would have to look for the docs. Something like `Registry(backend_path_or_url=None)` makes it much clearer what arguments the Registry can receive.

Unless really needed, I think explicitly taking parameters makes the code much easier to read.

**Comment by pwalsh** [comment]
@vitorbaptista agreed.
