### ISSUE TITLE
Convert README to reStructuredText so it looks good on PyPI

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-registry-py#7]

**Comment by vitorbaptista** [comment]
http://pandoc.org/try/ converted the README with no issues :+1:

**Comment by pwalsh** [comment]
hmm. not too excited about this. I much prefer we standardise on markdown for contributors on github, rather than rst for a handful of readers on pypi.

**Comment by brew** [comment]
+1 @pwalsh

**Comment by pwalsh** [comment]
@vitorbaptista please revert.

**Comment by vitorbaptista** [comment]
GitHub supports both Markdown and rst, so it doesn't make much difference. The difference is only when writing the README, which should be quite rare and painless.

Actually, I think reStructuredText is more common in Python packages than Markdown (probably because of pypi). See some examples:

https://github.com/django/django/blob/master/README.rst
https://github.com/Pylons/pylons/blob/master/README.rst
https://github.com/pypa/pip/blob/develop/README.rst
https://github.com/kennethreitz/requests/blob/master/README.rst
https://github.com/zzzeek/sqlalchemy/blob/master/README.rst
https://github.com/ckan/ckan/blob/master/README.rst

I'm OK with reverting, though. It's not a big issue.

**Comment by brew** [comment]
Just my experience: I hate updating docs written in RST, so I'm less likely to update them. I consider Pypi's lack of support for md a bug.

**Comment by pwalsh** [comment]
I've also done my share of readme's in [RST](https://github.com/pwalsh/moment/blob/master/README.rst) but can never remember the syntax.

**Comment by vitorbaptista** [comment]
It would be great if PyPI supported markdown, but I don't think it will anytime soon. I'm also more used to markdown, but using rst doesn't bother me.

In the end, shall I keep it or revert? I'm OK with both.

**Comment by femtotrader** [comment]
You may consider https://github.com/msabramo/setuptools-markdown

**Comment by vitorbaptista** [comment]
Wow, good job on handling that guy's aggressiveness, @femtotrader :clap: 

Anyway, I wouldn't like to add a dependency just to write markdown instead of rst. Too much hassle for a few lines of text. I'm OK with either keeping it as it is or reverting this issue. I just don't want to spend too much time bikeshedding here.

**Comment by roll** [comment]
Conversion with `pandoc` can be part of `Travis` build before upload to PyPi I suppose. It will be just a dev dependency.

**Comment by pwalsh** [comment]
Request to revert still stands: OKI uses markdown for readme ;).

**Comment by vitorbaptista** [comment]
Done :+1:
